#ifndef HANOITOWERSPROTOCOL_GLOBAL_H
#define HANOITOWERSPROTOCOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HANOITOWERSPROTOCOL_LIBRARY)
#  define HANOITOWERSPROTOCOL_EXPORT Q_DECL_EXPORT
#else
#  define HANOITOWERSPROTOCOL_EXPORT Q_DECL_IMPORT
#endif

#endif // HANOITOWERSPROTOCOL_GLOBAL_H
